version: '3'
#https://codesandbox.io/s/movie-seat-booking-xcmdj?file=/package.json:0-571

services:
  #API
  app:
    build:
      context: ./app
    working_dir: /opt/server
    env_file:
      - .env
    restart: always
    expose:
      - '3000'
    depends_on:
      - db
    command: npm run start

  # Контейнер с базой данных
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db_data:/docker-entrypoint-initdb.d
    expose:
      - '5432'
    restart: always

  # Контейнер с nginx
  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
      - db
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
      
    restart: always



networks:
  network: {}

volumes:
  postgres: